name: Tests

on: 
  push:
      paths-ignore:
      - 'README.md'
      - 'LICENCE'
      - '.gitignore'
      - '.githooks/'
      - '.github/workflows/build.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the code
      uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Check formatting
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
        args: --check

    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test