name: Publish

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Git Fetch Unshallow
      run: git fetch --prune --tags --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Output semver
      id: set_semver
      run: |
        if [[ ${{ env.branch }} == 'main' ]];
        then
          echo "::set-output name=semVer::$GitVersion_MajorMinorPatch"
        else
          echo "::set-output name=semVer::$GitVersion_SemVer"
        fi